# Generated by Django 5.0.3 on 2024-04-10 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(max_length=100)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_routines', to='workout_app.workout')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutRoutineDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('workout_routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='workout_app.workoutroutine')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutRoutineDayMuscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle', models.CharField(max_length=100)),
                ('workout_routine_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muscles', to='workout_app.workoutroutineday')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutRoutineDayMuscleExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.JSONField()),
                ('workout_routine_day_muscle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout_app.workoutroutinedaymuscle')),
            ],
        ),
    ]
