# Generated by Django 5.0.3 on 2024-04-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='video_url',
            field=models.JSONField(),
        ),
    ]
